### ISSUE TITLE
No streamer mode button v2

### ISSUE THREAD

**Issue by Bizarrebra** [prettierlichess/prettierlichess#103]
Hello guys! I'm back again with my "beloved" issue: no streamer mode available. It already happened to me once (please see issue #79), but that time the responsible was my antivirus. I then temporarily stopped it, and the streamer option was there. This time I made sure to disable my new antivirus (another brand) and try again, but the "Enable vertical layout" is nowhere to be seen, so I'm pretty sure it's not the antivirus this time. Can you guys reproduce the issue? Any ideas? Thanks in advance!

**Comment by kieferro** [comment]
Hello, thank you for reporting this bug.
I can't reproduce it unfortunately and it's not so easy to figure out remotely what the problem could be. But if it's important to you then you could try a few things so that I could maybe find the cause of the problem or at least narrow it down.

If you want to do that, here would be a guide to steps that would help me get more information about the problem:
- Go to Lichess and start a game (ideally with Stockfish so the game doesn't get aborted).
- Open the Developer Tolls with F12 or Ctrl+Shift+j.
- Switch to the ```Console``` tab
- Type the following command into the console and press Enter: ```document.querySelector(".round")```
You should now see either `null` or something like ```<main class="round">```.
- Do the same with the following command: ```document.querySelector(".streamerButton")```
- Send me the two outputs from the console

**Comment by kieferro** [comment]
Soon the new version (3.5.0) should be released. It also contains a debug output feature, which replaces the steps I described in my last message. If you want, feel free to follow [this guide](https://github.com/prettierlichess/prettierlichess/blob/e30fe44140559e58e7a950ea16ea99cf2e337d6a/CONTRIBUTING.md#read-debug-output) and screenshot the result or copy the text. This will make it much easier to reproduce the bug.
