### ISSUE TITLE
Looking for someone to take over

### ISSUE THREAD

**Issue by noahsemus** [prettierlichess/prettierlichess#106]
Hello everybody. Firstly I'd like to thank you all for using the extension and helping to contribute to its development, the chess community (and chess dev community) is truly amazing. However, as you all have noticed by now this repo has been quite barren. Unfortunately work has been very busy and other side projects have come up, and I have found myself without the time to maintain the extension. 

If there is anyone who would be interested in taking over the repo (and chrome extension listing in the store) just let me know. I can transfer the repo easily enough, but we can work together to transfer the extension listing as it's a little more annoying. 

Thanks again, everyone!

**Comment by kieferro** [comment]
Hi, I haven't known this repo for long, but I got quite a bit involved with it a few months ago and also created some PRs. So I could offer to help a bit with the management of the repo. I wouldn't feel comfortable being in charge all by myself, but I'm happy to help and if you'd like, I could also take care of reviewing the current PRs and closing as many current issues as possible so that at least the current stuff gets worked on. Then maybe in the long run another solution could be found.

Let me know what you think
Many greetings

**Comment by noahsemus** [comment]
Thanks @kieferro! I'd be glad to add you to the repo so you could help manage it. Will do so today or tomorrow!

**Comment by kieferro** [comment]
Thanks, happy to help @noahsemus 
(I don't mean to rush, but just in case you don't know: I did join the organization, but the settings seem to be such that I still don't have write access to the repo).

**Comment by noahsemus** [comment]
My bad. I've made you an owner. You should have full access.

**Comment by kieferro** [comment]
@noahsemus I think enough things have changed since the last release that it would be worth publishing a new version to actually remove the bugs from the official version and not just fix them in the repo.
What is the procedure for this? Do you want to publish the official versions to the stores or how do we do that?

**Comment by noahsemus** [comment]
Sorry for not getting to this sooner, we've had no AC in a heatwave so it's been a struggle!

Yes, I can publish the new versions to both the FF and chrome stores when needed. Shoot me an email at noahsemus@gmail.com anytime you have made enough changes to warrant a new version! I'll make sure to get it updated hopefully within a day or two (or if it's really busy within the week)

**Comment by kieferro** [comment]
> Sorry for not getting to this sooner

No problem, all good.

Thank you for publishing the current version. That sounds good: I'll send an email when I'm ready again 👍

**Comment by kieferro** [comment]
Closing this for now
