### ISSUE TITLE
Daily Puzzle Obscured by Tournament Winners Column

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#107]
This is a new issue that popped up today
![tournament winners obscuring daily puzzle](https://user-images.githubusercontent.com/104811236/182268148-ab70009c-e4ed-4383-8abd-4f60fedf30c6.PNG)
.

**Comment by kieferro** [comment]
Thanks for reporting the bug!
Unfortunately, I can't reproduce it on my system. Which browser (name and version) are you using?

**Comment by TheHypnotist333** [comment]
I'm using the latest version of chrome

**Comment by TheHypnotist333** [comment]
I don't know what the version number is but I just update it today and the issue is still there.

**Comment by TheHypnotist333** [comment]
It's strange because I didn't have this issue until 2 days ago. I am on lichess every day and usually do the daily puzzle lol

**Comment by kieferro** [comment]
I also use the latest version of Chrome (you can see the exact number under the three dots at the top right -> Help -> About Google Chrome. It should be something like `104.0.5112.81` with the latest version).

> It's strange because I didn't have this issue until 2 days ago.

I changed some files on the repo yesterday but we didn't publish anything to the Chrome Store since May, so that's pretty strange. I would normally guess that Lichess simply changed something on the website, but then I would have to have the same problem. 

It's pretty hard to figure out remotely what the problem might be. 
Another thing that might help is to run the extension alone in an Incognito Windows (to see if the problem exists there as well). Some problems do not occur there, for example because they are caused by other extensions or because lichess behaves differently depending on whether you are logged in.
If you want to try this, you have to go to the Extensions page, click on Prettierlichess, then on Details and activate `Allow in Incognito`. If you use other extensions, they should ideally not be activated in Incognito. Then you can open an Incognito window with Lichess and see if the problem still exists.
Maybe with this information I can narrow down the cause of the problem, but I can't promise anything.

**Comment by TheHypnotist333** [comment]
I tried it in incognito mode and the problem went away until I logged in in incognito mode, then it came back. The same is true for regular mode. There is only the issue if I am logged in. Also, I have two computers and it is the same issue on both computers. What does this mean?

**Comment by kieferro** [comment]
> the problem went away until I logged in in incognito mode, then it came back



Ok, that's very strange, but it's probably related to the fact that the appearance of the website changes when you are logged in.
That helps me for the search, but I still don't really understand where the problem comes from. I'll see what I can do and I'll let you know if I find out anything.
What else might help is to uninstall the extension once and add it again (the usual fix, I know, but I sadly can't offer much more), but you might have already tried that yourself.

**Comment by millsaj** [comment]
I've been getting this issue as well. Also only when logged in. I'm using firefox 105 (although have been seeing the issue for a while so likely also on other versions). 

Since I can replicate it, I can have a go at raising a PR for it if you want?

**Comment by kieferro** [comment]
> Since I can replicate it, I can have a go at raising a PR for it if you want?

That would be great. It's very hard for me to fix bugs that I can't replicate. So I would be very grateful if you are able to solve the problem. Just open a PR and I'll review. If you need any help, feel free to ping me.
