### ISSUE TITLE
Desktop breakpoints broken

### ISSUE THREAD

**Issue by noahsemus** [prettierlichess/prettierlichess#122]
Latest update seems to have broken a couple of desktop breakpoints when not at the largest size.

![image](https://user-images.githubusercontent.com/33107099/201481850-35a55f7d-c8ab-449e-acd3-bbe50cd74187.png)

**Comment by kieferro** [comment]
Thanks for reporting. I found a fix, although I'm still pretty confused. My fix was to remove the `!important` label from the injected `grid-template` style rules. With the way the stylesheet is injected, this doesn't change whether the rule is applied (So the label actually wasn't necessary). But it seems like `!important` somehow still makes a difference in how the grid is displayed.

Also, it runs with the current version in Firefox without any problems, which confuses me even more.

Whatever, the problem is fixed. But I will still try to find out why it occurred. If anyone has any ideas, they would be appreciated.
