### ISSUE TITLE
Add option to use for lichess-based sites

### ISSUE THREAD

**Issue by ratHippo** [prettierlichess/prettierlichess#149]
There are many websites based on lichess, such as [playstrategy.org](https://playstrategy.org). Is it possible to make it so that you can input domains, allowing you to use this extension on lichess-based sites?

**Comment by kieferro** [comment]
Even though I really understand the request and I am happy that the design is so good that it is missed on other sites, I'm afraid that what you're asking for won't be possible.
I have injected the scripts into [playstrategy.org](https://playstrategy.org/) and [lishogi.org](https://lishogi.org/) to see if it works over there too. Most of the CSS rules seem to work but there are also some problems, especially with the basic layout:

![Screenshot 2023-04-14 at 23-17-02 The best free adless Shogi server](https://user-images.githubusercontent.com/81773954/232157214-ff6f94e5-3e67-4303-88d8-8ccf72702af5.png)

![Screenshot 2023-04-14 at 23-17-06 The two player strategy games platform  Chess Draughts Shogi Xiangqi and more!](https://user-images.githubusercontent.com/81773954/232157218-766a9dd2-d4f0-4af2-be4f-f60dd6ac5703.png)

Since the websites are only similar to lichess and not exactly the same they would require big changes in the CSS rules. In addition to that it is not possible for one extension to differentiate between the sites and adjust the CSS accordingly since this part of the injection happens without javascript.
I'm sorry, but rolling out an additional extension for other websites would be a lot of work (and I'm not really convinced that the demand is high enough to justify this). If you or anybody else wants to fork this repo and maintain a second extension for a different site, I'm always happy to contribute of help with questions. But we will not pick that up as our own project.
