### ISSUE TITLE
HTML Popup doesn't work

### ISSUE THREAD

**Issue by HaydenBerberich** [prettierlichess/prettierlichess#151]
I feel like this is most likely an error on my part, but I'm not sure how to resolve it. Whenever I load the unpacked extension the HTML popup doesn't work in Lichess: no color selectors appear, import/export/reset buttons don't work, board colors tab doesn't open. Do you know what the issue is?

**Comment by kieferro** [comment]
Yes, the problem is that the extension needs to be bundled with [Webpack](https://webpack.js.org/) first. If you just want to manually load a release, feel free to look at the [releases tab](https://github.com/prettierlichess/prettierlichess/releases). For the releases > 3.7.0 there is a zip file with a bundled build which you can unzip and load.

If you want to use the very latest version or develop yourself, then you would have to [install node and npm](https://nodejs.org/en/download).
More information on how to build with webpack can be found [here](https://github.com/prettierlichess/prettierlichess/blob/master/.github/CONTRIBUTING.md#build-and-test-workflow).

If you have any further questions, feel free to comment here.
