### ISSUE TITLE
Prettier chess.com

### ISSUE THREAD

**Issue by dxkill** [prettierlichess/prettierlichess#152]
Could you make a similar extension for chess.com? that would be really cool.

**Comment by kieferro** [comment]
I'm glad to see that the extension is so well received that it is desired for other sites as well. But as I have already answered in [response to a similar request](https://github.com/prettierlichess/prettierlichess/issues/149#issuecomment-1509298600):

> Since chess.com is only similar to lichess and not exactly the same that would require a complete rewrite of the CSS rules. I don't know if you are aware of that, but the restyling is completely manually created and must be adjusted again and again. In addition to that it is not possible for one extension to differentiate between the sites and adjust the CSS accordingly since this part of the injection happens without javascript.
> I'm sorry, but rolling out an additional extension for other websites would be a lot of work (and I'm not really convinced that the demand is high enough to justify this). If you or anybody else wants to fork this repo and maintain a second extension for a different site, I'm always happy to contribute of help with questions. But we will not pick that up as our own project.

So you would have to build a completely new extension, which would have to be created and customized exactly for chess.com. This is an enormous amount of work and especially for chess.com it is much more difficult to develop extensions, because the site is less clearly structured and not open-source.
If you want to create an extension, I am happy to help with questions or problems, but we as the prettierlichess team will not maintain the project independently.
