### ISSUE TITLE
New large board on home page is taller than available space

### ISSUE THREAD

**Issue by crafty35a** [prettierlichess/prettierlichess#170]
At some point a few weeks ago the home page layout changed to be full width (the central column stretches to fill all available space), and it's resulting in the board being taller than the available screen space. Is there any way I can make the center column less wide? I imagine this would be an even bigger issue on an ultrawide monitor (although I don't have one personally)

![image](https://github.com/prettierlichess/prettierlichess/assets/1082003/8754c260-8984-49cc-977b-528c4b05a602)

**Comment by crafty35a** [comment]
I just realized this was apparently fixed: https://github.com/prettierlichess/prettierlichess/pull/161/commits/aa1796f9e3ebc80670fb7b3f42bfe8dd48d00088#diff-c45260538e7113033e56d8937aeaff3227d3b4bece48f7642b118f345d0cbb65

But I am not seeing the fix in the version available on the Chrome web store (3.8.2), is it not up to date?

**Comment by kieferro** [comment]
Yes, you are right, this is already fixed in the codebase but not in the store version. I actually wanted to wait for some other changes before releasing the latest version, but those seems to take more time than I expected. That's why I just [published the latest version here on Github](https://github.com/prettierlichess/prettierlichess/releases/tag/v.3.9.0) and initiated a release to the stores. Version 3.9.0 should be online soon.
