### ISSUE TITLE
Layout is squashed

### ISSUE THREAD

**Issue by akilou** [prettierlichess/prettierlichess#192]
This is what lichess looks like with Prettier Lichess turned on.
![image](https://github.com/prettierlichess/prettierlichess/assets/4934676/e2515db3-94fb-43e6-8aea-990e36a0acbb)

and this is what it looks like with it turned off.
![image](https://github.com/prettierlichess/prettierlichess/assets/4934676/6717e689-35aa-49d7-a124-38a0139b7acf)

**Comment by crafty35a** [comment]
Exact same issue here, just started today. I am on a 1440p using the "1080p layout" option (though the 1440p layout option does not look much better).

**Comment by TheHypnotist333** [comment]
Same with me

**Comment by joshuabugg** [comment]
Same for me, 1080p display on firefox 120.0.1 if that helps.

**Comment by momboco** [comment]
Same here!

**Comment by itsREV** [comment]
Same issue here using firefox 120.0.1 on ultrawide (3440x1440)

**Comment by oscarc231** [comment]
Same. It happens in Firefox 121.0 (64-bit) and Vivaldi 6.5.3206.42 (Stable channel) (x86_64), both macOS. I have to change to "Lichess layout."

**Comment by wongdq** [comment]
I think its caused by the (newly added?) _lobby feed div_ which does not have a specified place in the grid_template_area. You should be able to see this (out of place feed) when you scroll all the way down

![lichess_lobby_feed](https://github.com/prettierlichess/prettierlichess/assets/24638879/2b97a4ed-3ac1-4e76-bc23-b95afd154f6f)

A temp fix would just to delete this div whenever you are on the home page of lichess. (Right-click the top of the feed box > Inspect > Delete the div in the DevTools) You'll have to do this each time you refresh the page.

![feed_div](https://github.com/prettierlichess/prettierlichess/assets/24638879/9feced3f-5e69-43a4-8f2c-c55a16395866)

**Comment by akilou** [comment]
Yeah, that's exactly the problem and your proposed solution works. Although, I'm not going to do that every time. I go back to the lobby regularly between games.

**Comment by ama29** [comment]
Pull request [created here](https://github.com/prettierlichess/prettierlichess/pull/196) to address the issue

**Comment by Eternal-0-Darkness** [comment]
i used ublock to remove that feed
it will remove the feed automatically if you block it

**Comment by akilou** [comment]
Interesting work around. But ublock won't select that feed as a thing. Best I can do is select the little icons on the left of it.

![image](https://github.com/prettierlichess/prettierlichess/assets/4934676/3337178d-bd02-49cd-a93e-27d773fe065c)

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
