### ISSUE TITLE
Board Colors Not Working 

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#97]
I'm using the extension through Kiwi on my tablet (Galaxy Tab A). The board color options do not change the board color, everything else works. I have the same setup on my phone and it works but not on my tablet.

**Comment by TheHypnotist333** [comment]
I realized this is because I'm on night mode inside Kiwi. If I turn off night mode the board colors are there again.

**Comment by kieferro** [comment]
> I realized this is because I'm on night mode inside Kiwi.

Yes, I can replicate the problem now. I'm leaving this issue open as the board colours should work independent of the theme setting. But this should make it way easier to fix the bug.

**Comment by kieferro** [comment]
Okay, I have solved the problem now, even though it was relatively difficult. We will publish the fix in the next few days.

**Comment by TheHypnotist333** [comment]
Thank you! I saw that it was updated on github the other day but not in the
chrome store yet. Looking forward to trying it out

**Comment by kieferro** [comment]
I'm sorry, but I'm afraid I'll have to revert the fix for this bug after all. Using other methods to create the board has created a lot of other bugs. And as long as I haven't solved all of them, it seems to me the most sensible thing to do is to revert to the old method for now. We will probably release an update soon, which will roll back these changes and thus produce the bug again. Sorry for the inconvenience, I'll try to find a way to fix this bug here anyway.

**Comment by TheHypnotist333** [comment]
Alright I understand. Is there a way for me to keep using this version when
you revert back? I stopped using the extension during the last version
because I couldn't see the board for analysis. This version works fine, the
board colors are just slightly different which is no big deal for me.

**Comment by kieferro** [comment]
> Is there a way for me to keep using this version when you revert back?

Yes, I've added a [build version to the 3.7.1 release](https://github.com/prettierlichess/prettierlichess/releases/download/v.3.7.1/build-3.7.1.zip). You can add it simply by downloading it to your phone, removing the current installation and going to the extension overview and selecting `+(from .zip/.crx/.user.js)`. Then simply select the build folder to install the extension.

> I couldn't see the board for analysis. This version works fine

Just to make sure there is no communication problem: The fix for the analysis board (#131) will remain, as will all the other changes added by `v3.7.0`. The only thing I will temporarily take back is the ability to set Board Colors on Kiwi in Darkmode.

**Comment by TheHypnotist333** [comment]
Oh I understand now. That's all good then, I don't need to use dark mode.
Thanks for letting me know.

**Comment by kieferro** [comment]
> I don't need to use dark mode.

Does this mean that the error does not bother you? If it is a problem for you, then I am happy to find a solution. But because this is not a real bug of the extension, but related to how Kiwi creates the dark mode, it is quite difficult to find a solution that works everywhere.
So if this bug is really not a problem for you, then I would close it and, if someone else is bothered by this problem (I have the feeling our Kiwi user base is rather small), the person is welcome to open it again.

**Comment by TheHypnotist333** [comment]
It's not a real issue for me personally. I use this app on Kiwi a lot but
not in night mode.
