### ISSUE TITLE
Friends List Blurred Out

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#98]
When I am on the home screen the friends list at the bottom of the page is blurred out. It is there until I hover my mouse over it. If I go to any other page the friends works fine.
I cannot easily capture this happening in a screenshot as my mouse needs to be hovering over the friends list for it to appear (or not).

**Comment by TheHypnotist333** [comment]
![PXL_20220706_164325081](https://user-images.githubusercontent.com/104811236/177601632-7e10f98a-4efc-4949-806e-6c1727a11e4a.jpg)
![PXL_20220706_164335763](https://user-images.githubusercontent.com/104811236/177601677-8d8fe4e4-9367-4edd-8afc-af9eb394ba7b.jpg)

See in the first picture it's there. The second picture I move my mouse over it and it disappears. It won't allow me to click on it. This is Google chrome.

**Comment by kieferro** [comment]
I'm very surprised about this bug, because the extension doesn't really change much on this button.
If you want to help me debug it, feel free to follow the steps below. I know it's cumbersome, but that's the best I can offer if it's important to you that the issue is resolved:

- Open the developer console with _F12_.
- Click on the three dots in the upper right corner and use the pop-out option, so that the console is displayed in a separate window.
- Go to the Lichess start page
- Change in the console to the _Console_ tab
- Copy the following code into the console:
  ```let x = setInterval(function(){console.log(document.querySelector(".friend_box_title"))}, 1000);```
    and press Enter. This will cause the console to output every second whether the button is present. Normally, something like `<div class="friend_box_title">` should appear in the console every second. Try to see if this is the case when you hover over the button. That would definitely help me as information.

I still can't promise that I'll get the problem solved then, but it's the best I can offer.

**Comment by TheHypnotist333** [comment]
I did what you said but i'm not sure what I'm looking for. I entered the code and that other line of code appeared every second, when I hovered over the friends list nothing happened with the code. Not sure if I did it right.
On a side note I noticed this issue is only present when I use Lichess in full screen mode or open it in its own window from the desktop shortcut. I typically use Lichess in full screen (F11) and use a desktop shortcut to open it.

**Comment by kieferro** [comment]
To explain in more detail what I intended with this test: It makes a difference whether the button is actually deleted or just hidden. This code outputs every second whether the button still exists. If it still exists, then something like `<div class="friend_box_title">` is the output. Otherwise `null`.
That means there are two possibilities:
1. You start the code, hover over the button (it disappears) and while the button is invisible only `null` is output, because the button was actually deleted.
2. You start the code and even while you hover over the button and don't see it anymore, it still prints `<div class="friend_box_title">` or something similar. This means that the button still exists, but is just hidden.

If I understand you correctly, then 2. was the case for you?

> On a side note I noticed this issue is only present when I use Lichess in full screen mode or open it in its own window from the desktop shortcut. I typically use Lichess in full screen (F11) and use a desktop shortcut to open it.

Thanks for mentioning that, that might be helpful as well. I tried to reproduce the bug with Lichess in full screen, but unfortunately without success.

Do I understand correctly, the bug also occurs when Lichess is not in full screen, but is opened via a screenshot? That is, it actually makes a difference if you open a new Chrome window and go to lichess or open lichess via a shortcut?

**Comment by TheHypnotist333** [comment]
Ok I tried it again. The button still exists. It still prints that code even when it "disappears".
Yes it makes a difference if I open a new chrome window vs opening via shortcut.
This behavior is slightly different now than when I posted the original picture. It doesn't completely disappear anymore, it just goes behind the donation panel when I hover over it. Actually the far right edge of the friends list still sticks out from behind the donation panel so I am still able to click on it if I mouse over the far right edge. In fact, if I scroll below the donation and swag store panels I can use the friends list normally.

**Comment by TheHypnotist333** [comment]
I am using a different color profile now, maybe that's why it looks different now. With that other profile from the original photo I think maybe it was the same behavior as now but it seemed to disappear because of the color scheme. This new color scheme is more transparent and I can see that the friends list goes behind the donation panel. Hope this helps.

**Comment by kieferro** [comment]
> Ok I tried it again. The button still exists. It still prints that code even when it "disappears".

Okay, that's what I expected. Thanks for checking again.




> In fact, if I scroll below the donation and swag store panels I can use the friends list normally.

So the problem is really just that the other hoverable elements of the page go over the button, even when the mouse is in the area of the button?
Because I can actually replicate that, I had never scrolled down for testing before and Swag Store and Donate never got in the way.
That should be a relatively easy fix. I'll take care of it and we'll release a patch in the next few days.

**Comment by TheHypnotist333** [comment]
Yes that's it. Thanks!
